spring:
  application:
    name: GATEWAY-SECURE-SERVICE

server:
  port: 8980

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000